apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-bootstrap
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: in-cluster
  source:
    path: root-app
    repoURL: "https://github.com/Sotatek-HuyNguyen17/ArgoCD-App-Of-App-Pattern"
    targetRevision: HEAD #latest revision on the branch
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
