apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-bootstrap
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: shared-service
  source:
    path: infrastructure
    repoURL: "https://github.com/Sotatek-HuyNguyen17/ArgoCD-App-Of-App-Pattern"
    targetRevision: HEAD #latest revision on the branch
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
